name: Deploy on EC2 (Self-Hosted Runner)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop existing container
        run: |
          docker stop bookmyshow || true
          docker rm bookmyshow || true

      - name: Remove old image (optional) 
        run: |
          docker rmi bookmyshow-app || true

      - name: Debug file structure
        run: |
          pwd
          ls -la

     
